CREATE TABLE USUARIOS (
    ID INT NOT NULL GENERATED ALWAYS AS IDENTITY,
    NAME VARCHAR(50) NOT NULL,
    ADDRESS VARCHAR(100) NOT NULL,
    SYS_START TIMESTAMP(12) GENERATED ALWAYS AS ROW BEGIN NOT NULL,
    SYS_END TIMESTAMP(12) GENERATED ALWAYS AS ROW END NOT NULL,
    TRANS_START TIMESTAMP(12) GENERATED ALWAYS AS TRANSACTION START ID IMPLICITLY HIDDEN,
    PERIOD SYSTEM_TIME(SYS_START, SYS_END),
    PRIMARY KEY (ID)
);

CREATE TABLE USUARIOS_HYSTORY LIKE USUARIOS;
ALTER TABLE USUARIOS ADD VERSIONING USE HISTORY TABLE USUARIOS_HYSTORY;

CREATE TABLE SEGURO (
  ANO DATE NOT NULL ,
  MODELO VARCHAR(20) NOT NULL ,
  MARCA VARCHAR(20) NOT NULL ,
  PRECIO_FACTURA DECIMAL(7,2) NOT NULL ,
  NUM_MOTOR VARCHAR(30) NOT NULL ,
  NUM_SERIE VARCHAR(30) NOT NULL ,
  PLACA VARCHAR(10) NOT NULL,
  
  PRECIO_SEGURO DECIMAL(6,2) NOT NULL,
  COVERTURA INT NOT NULL,
  ESTATUS INT NOT NULL DEFAULT 1,
  cstart DATE NOT NULL,
  cend DATE NOT NULL,
  period business_time(cstart, cend),

  SYS_START TIMESTAMP(12) GENERATED ALWAYS AS ROW BEGIN NOT NULL,
  SYS_END TIMESTAMP(12) GENERATED ALWAYS AS ROW END NOT NULL,
  TRANS_START TIMESTAMP(12) GENERATED ALWAYS AS TRANSACTION START ID IMPLICITLY HIDDEN,
  PERIOD SYSTEM_TIME(SYS_START, SYS_END),
  PRIMARY KEY (PLACA, business_time WITHOUT overlaps)
);

CREATE TABLE SEGURO_HYSTORY LIKE SEGURO;
ALTER TABLE SEGURO ADD VERSIONING USE HISTORY TABLE SEGURO_HYSTORY;

--Trigger
create trigger CANCELACION
  after update on SEGURO referencing
  old as old_values
  new as new_values
  for each row mode db2sql
  begin atomic
    update estadisticas
      set empDespedidos = empDespedidos +1;
  end

--En update no se puede disminuir las coverturas de poliza
CREATE  INSURANCErestriction
BEFORE UPDATE OF  ON INSURANCE
REFERENCING OLD AS old_values NEW AS new_values
FOR EACH ROW mode DB2SQL
WHEN ( BETWEEN )
BEGIN
atomic
SIGNAL SQLSTATE '56001' ('No se puede incrementar mas del 30%');
END
